### ISSUE TITLE
Crashes on hundred-player demos

### ISSUE THREAD

**Issue by Thespikedballofdoom** [drunderscore/CastingEssentialsNext#10]
I'm sorry

**Comment by drunderscore** [comment]
Apology accepted. I'll look into how broken this is and what is breaking this, unsure how trivial it is.

**Comment by drunderscore** [comment]
Fixed in bde0cae

**Comment by drunderscore** [comment]
Note there are other issues with 100 player demos, both in regards to CastingEssentials Next and the demos themselves (I believe some of them to be broken/recorded incorrectly).
