### ISSUE TITLE
Include K/A/D on target ID

### ISSUE THREAD

**Issue by drunderscore** [drunderscore/CastingEssentialsNext#3]
This requires srctv+. Should be hidden without it -- better not to lie.

**Comment by coreobs** [comment]
Could also add this to playerpanels, and have both setup with the classic 0/1 off/on toggle commands so HUD authors can toggle it off (and say embedded chargebars/loadouts/etc on for a pseudo webhud stats panel that can be toggled).

**Comment by drunderscore** [comment]
Implemented in 2e5491e, will delegate to HUD authors to see if this is actually proper and useful.
